// Diccionario de strings en español — nunca hardcodear en componentes
export const dict = {
    marca: {
        nombre: 'RAM Informática',
        tagline: 'Tecnología y iPhones en Santa Rosa, La Pampa',
        descripcion: 'RAM Informática — Tu tienda de confianza en Santa Rosa, La Pampa. Venta de iPhones, PlayStation, Samsung, Motorola y tecnología premium con los mejores precios de Argentina. Envíos a todo el país.',
    },
    nav: {
        inicio: 'Inicio',
        productos: 'Productos',
        categorias: 'Categorías',
        ofertas: 'Ofertas',
        contacto: 'Contacto',
        nosotros: 'Nosotros',
        servicios: 'Servicios',
        comoComprar: 'Cómo comprar',
        admin: 'Administración',
    },
    hero: {
        titulo: 'Tecnología premium',
        subtitulo: 'a precios muy competitivos',
        descripcion: 'Celulares, Macbooks, Consolas de Video Juegos, Camaras Fotográficas, Tablets, y mucho más...Precios en dólares y pesos actualizados a diario.',
        cta: 'Ver productos',
        ctaSecundario: 'Ver categorías',
    },
    productos: {
        titulo: 'Nuestros productos',
        nuevo: 'Nuevo',
        reacondicionado: 'Reacondicionado',
        usado: 'Usado',
        oem: 'OEM',
        verDetalle: 'Ver detalle',
        agregarCarrito: 'Agregar al carrito',
        sinStock: 'Sin stock',
        pocaExistencia: 'Pocas unidades',
        enStock: 'En stock',
        filtrar: 'Filtrar',
        ordenar: 'Ordenar',
        buscar: 'Buscar productos...',
        resultados: (n: number) => `${n} producto${n !== 1 ? 's' : ''} encontrado${n !== 1 ? 's' : ''}`,
    },
    precio: {
        precioUSD: 'Precio en dólares',
        precioARS: 'Precio en pesos',
        actualizadoHace: 'Actualizado hace',
        minutos: 'minutos',
        dolarBlue: 'Dólar Blue',
        venta: 'Venta',
    },
    categorias: {
        titulo: 'Categorías',
        todas: 'Todas',
        explorar: 'Explorar',
        iphone: 'iPhones',
        samsung: 'Samsung',
        motorola: 'Motorola',
        jbl: 'JBL Audio',
        gaming: 'Video Juegos',
        airpods: 'AirPods',
        appleWatch: 'Apple Watch',
        ipad: 'iPad',
        macbook: 'MacBook',
        televisores: 'Televisores',
    },
    admin: {
        titulo: 'Panel de Administración',
        productos: 'Productos',
        categorias: 'Categorías',
        marcas: 'Marcas',
        proveedores: 'Proveedores',
        inventario: 'Inventario',
        importarPrecios: 'Importar Precios',
        nuevo: 'Nuevo',
        editar: 'Editar',
        eliminar: 'Eliminar',
        guardar: 'Guardar',
        cancelar: 'Cancelar',
        confirmarEliminar: '¿Estás seguro de eliminar este elemento?',
        eliminado: 'Elemento eliminado',
        guardado: 'Cambios guardados',
        error: 'Ocurrió un error',
        cargando: 'Cargando...',
        nombre: 'Nombre',
        descripcion: 'Descripción',
        categoria: 'Categoría',
        marca: 'Marca',
        precio: 'Precio (USD)',
        stock: 'Stock',
        activo: 'Activo',
        condicion: 'Condición',
        sku: 'SKU',
        color: 'Color',
        almacenamiento: 'Almacenamiento',
        conectividad: 'Conectividad',
    },
    errores: {
        noEncontrado: 'Página no encontrada',
        errorCarga: 'Error al cargar los datos',
        intentarNuevo: 'Intentar nuevamente',
    },
    footer: {
        derechos: '© 2026 RAM Informática. Todos los derechos reservados.',
        mediosPago: 'Medios de pago',
        contacto: 'Contacto',
        redes: 'Redes sociales',
    },
} as const
